### ISSUE TITLE
Installation issues

### ISSUE THREAD

**Issue by akshaykakde** [mattlyon93/face-comparison#1]
Could not find a version that satisfies the requirement face-compare (from versions: )
No matching distribution found for face-compare

Tried with pip2 & pip3 but still, it didn't work.

**Comment by mattlyon93** [comment]
Hmm, can I ask what operating system you are using?

Also, the pip page can be found [here](https://pypi.org/project/face-compare/), are you sure you're spelling the package name correctly?

**Comment by amuuth** [comment]
I ran into this issue as well, on Ubuntu. The version of python you are running isn't recent enough for pip3 to install face-compare. 

Try updating python3 to python3.7 or later on your machine.

**Comment by akshaykakde** [comment]
Okay.Let me check
________________________________

Star India
Akshay Kakade |
Star India
Email: akshay.kakade.vc@startv.com
STAR House, Urmi Estate, 95 Ganpatrao Kadam Marg, Lower Parel (W), Mumbai, 400013.
Consider the environment. Do you really need to print this email?
