### ISSUE TITLE
This is not an issue but question

### ISSUE THREAD

**Issue by JAY-TRIVEDI-007** [mattlyon93/face-comparison#19]
Hello,

I am new to open-cv and AI area but I am Full Stack Developer.
I have question that what does this mean?
Is that difference?

Distance between two images is 1.101289987564087

**Comment by m-lyon** [comment]
The model calculates an embedding (a vector) based on each of the two images. The 'distance' here is the result from taking the 2-norm of img_one_embedding minus img_two_embedding. It is a way of quantifying the difference between the two images, yes.
